config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

    before_action :set_image, only: [:show, :edit, :update, :destroy]

    def index
        @images = Image.all
    end

    def new
        @image= Image.new
    end

    def create
        @image = Image.new image_params
        @image.save

        redirect_to @image 
    end

    def show        
    end

    def edit        
    end

    def update
       @image.update image_params
       redirect_to @image
    end

    def destroy        
        @image.destroy
        redirect_to images_path
    end

    def set_image
        @image = Image.find params[:id]
    end

    private 
    def image_params
        params.require(:image).permit(:description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<div class="form-group">
    <%= form_for @image do |f|%>
        <%= f.label :description %><br>
        <%= f.text_field :description, class: 'form-control'%>
        <br>
        <%= f.label :picture %><br>
        <%= f.file_field :picture %>
        <br>
        <%= f.submit "enviar", class: 'btn btn-primary'%>
    <% end %>
</div>
    

app/views/images/_image.html.erb
<div class="col">
    <figure class="figure">
        <%= image_tag image.picture.medium.url, class: 'figure-img img-fluid rounded'%>
        <figcaption class="figure-caption"><%= image.description %> 
            <%= link_to 'Edit', edit_image_path(image)%>
            <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'sure?'}%>
        </figcaption>
    </figure>
</div>

app/views/images/edit.html.erb
<div class="container">
    <p>Editar Imagen</p>
    <%= render 'form' %>
</div>

app/views/images/index.html.erb
<div class="container">
    <div class="row">
        <%= render @images %>
    </div>
</div>

app/views/images/new.html.erb
<div class="container">
    <p>Crear Imagen</p>
    <%= render 'form' %>
</div>

app/views/images/show.html.erb
<%= image_tag @image.picture.medium.url, class: 'figure-img img-fluid rounded'%>
<%= @image.description%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apliprueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>